(in-package :las)

(setf binary-types:*endian* :little-endian)

(define-binary-string 32-char-string 32)
(define-unsigned float64 8)

(define-binary-struct number-of-point-by-return ()
  (npbr-0 0 :binary-type u32)
  (npbr-1 0 :binary-type u32)
  (npbr-2 0 :binary-type u32)
  (npbr-3 0 :binary-type u32)
  (npbr-4 0 :binary-type u32))

(define-binary-struct project-id-4 ()
  (pid4-0 0 :binary-type u8)
  (pid4-1 0 :binary-type u8)
  (pid4-2 0 :binary-type u8)
  (pid4-3 0 :binary-type u8)
  (pid4-4 0 :binary-type u8)
  (pid4-5 0 :binary-type u8)
  (pid4-6 0 :binary-type u8)
  (pid4-7 0 :binary-type u8))

(define-binary-class foo ()
  ((tab :binary-type )))
(define-binary-class public-header-block ()
  ((file-signature :binary-type (define-binary-string file-signature 4) :initform "LASF")
   (file-source-id :binary-type u16 :initform 0)
   (global-encoding :binary-type u16 :initform 0)
   (project-id-1 :binary-type u32 :initform 0)
   (project-id-2 :binary-type u16 :initform 0)
   (project-id-3 :binary-type u16 :initform 0)
   (project-id-4 :binary-type project-id-4
                 :initform (make-project-id-4))
   (version-major :binary-type u8 :initform 0)
   (version-minor :binary-type u8 :initform 0)
   (system-identifier :binary-type 32-char-string)
   (generating-software :binary-type 32-char-string)
   (file-creation-doy :binary-type u16 :initform 0)
   (file-creation-year :binary-type u16 :initform 0)
   (header-size :binary-type u16 :initform 0)
   (offset-to-point-data :binary-type u32 :initform 0)
   (number-of-variable-length-records :binary-type u32 :initform 0)
   (point-data-format-id :binary-type u8 :initform 0)
   (point-data-record-length :binary-type u16 :initform 0)
   (number-of-point-records :binary-type u32 :initform 0)
   (number-of-point-by-return :binary-type number-of-point-by-return
                              :initform (make-number-of-point-by-return))
   (x-scale-factor :binary-type float64 :initform 0)
   (y-scale-factor :binary-type float64 :initform 0)
   (z-scale-factor :binary-type float64 :initform 0)
   (x-offset :binary-type float64 :initform 0)
   (y-offset :binary-type float64 :initform 0)
   (z-offset :binary-type float64 :initform 0)
   (max-x :binary-type float64 :initform 0)
   (min-x :binary-type float64 :initform 0)
   (max-y :binary-type float64 :initform 0)
   (min-y :binary-type float64 :initform 0)
   (max-z :binary-type float64 :initform 0)
   (min-z :binary-type float64 :initform 0)
   (start-of-waveform-data-packet :binary-type u64)))
